### ISSUE TITLE
The time of training

### ISSUE THREAD

**Issue by super233** [microsoft/ProDA#1]
How long will each stage last based on the paper setting? 
I am training the stage1 on 2 Tesla V100-DGXS-32GB, and it takes 2 hours to train 1000 iters(about 1.3 epoch), it's a little slow, is this to be expected?

**Comment by panzhang0212** [comment]
It will take 36 hours in 4 Tesla V100-DGXS-32GB. Below is the training log:
[run_2020_12_01_06_27_02.log](https://github.com/microsoft/ProDA/files/6301751/run_2020_12_01_06_27_02.log)
As seen from the log, you can train fewer epochs if you want to get final result quickly.

**Comment by super233** [comment]
Thanks, and how about the stage2 and stage3?

**Comment by panzhang0212** [comment]
stage2 log:
[run_2020_11_09_15_38_50.log](https://github.com/microsoft/ProDA/files/6302304/run_2020_11_09_15_38_50.log)
stage3 log:
[run_2020_11_26_08_50_10.log](https://github.com/microsoft/ProDA/files/6302310/run_2020_11_26_08_50_10.log)

**Comment by ljjcoder** [comment]
@panzhang0212 It takes 36 hours for each stage, 108 hours in total right?
