### ISSUE TITLE
Can not reproduce in Gta5 -cityscape task.

### ISSUE THREAD

**Issue by ygjwd12345** [microsoft/ProDA#11]
We rerun your code following the default setting. The result is quite lower than reported(57.5%).
our result is as follows:
Overall Acc:     0.8863829080331662
Mean Acc :       0.6676762265179861
FreqW Acc :      0.8026627310122789
Mean IoU :       0.5486842157620068

**Comment by super233** [comment]
Hi, I'm also interested about the reproducibility, would you please report the MIoU of each stage described in paper, and provide the corresponding logs?

**Comment by panzhang0212** [comment]
please refer to #1 for the log

**Comment by ygjwd12345** [comment]
> Hi, I'm also interested about the reproducibility, would you please report the MIoU of each stage described in paper, and provide the corresponding logs?

Our stage3 log file is as follow
[run_2021_05_08_23_22_15.log](https://github.com/microsoft/ProDA/files/6460057/run_2021_05_08_23_22_15.log)

**Comment by panzhang0212** [comment]
It seems that your bs is 2, while our experiments use 4. If you try bs 2, you need to change learning rate to match your bs.

**Comment by ygjwd12345** [comment]
I never change the setting.

**Comment by panzhang0212** [comment]
if your bs is 4, the log should be 
![image](https://user-images.githubusercontent.com/30363822/122318862-59746400-cf52-11eb-8b6f-cb63c49e9375.png)
while your log is :
![image](https://user-images.githubusercontent.com/30363822/122318914-6f822480-cf52-11eb-8aef-5ff78b6cad47.png)
that is to say, the bs is not 4, thus the total iterations change.

**Comment by ygjwd12345** [comment]
> if your bs is 4, the log should be
> ![image](https://user-images.githubusercontent.com/30363822/122318862-59746400-cf52-11eb-8b6f-cb63c49e9375.png)
> while your log is :
> ![image](https://user-images.githubusercontent.com/30363822/122318914-6f822480-cf52-11eb-8aef-5ff78b6cad47.png)
> that is to say, the bs is not 4, thus the total iterations change.

thanks
