### ISSUE TITLE
what is the warm-up model? 

### ISSUE THREAD

**Issue by liuyk97** [microsoft/ProDA#12]
In the training processing of stage1, I need to download warm-up model (43.4 mIoU), and resume from it, but there seems no description of what dataset is it pretrained on. Is it pretrained on source dataset?
thank you

**Comment by panzhang0212** [comment]
It is pretrained by https://github.com/microsoft/ProDA/blob/9ba80c7dbbd23ba1a126e3f4003a72f27d121a1f/models/adaptation_modelv2.py#L143 function

**Comment by KaiiZhang** [comment]
> It is pretrained by
> 
> https://github.com/microsoft/ProDA/blob/9ba80c7dbbd23ba1a126e3f4003a72f27d121a1f/models/adaptation_modelv2.py#L143
> 
> function
Thanks for your great work!
What initialization weights do you use in the warmup stage? Could you please upload it. Thank you very much.
