### ISSUE TITLE
A Problem of Using Pretrained Model

### ISSUE THREAD

**Issue by flyingintoskyq** [microsoft/ProDA#13]
Hi~ I want to use the pretrained model "GTA5 -> Cityscapes". However, when running the command `python test.py --bn_clr --student_init simclr --resume ./pretrained/gta2citylabv2_stage3/from_gta5_to_cityscapes_on_deeplabv2_best_model.pkl`, I encountered an error that read `FileNotFoundError: [Errno 2] No such file or directory: '/mnt/blob\\Dataset/GTA5\\split.mat'`. So, could you please describe how to set the correct path, and how to configure the dataset? Thanks! :)

**Comment by HaoL20** [comment]
Download [read_mapping.zip](https://download.visinf.tu-darmstadt.de/data/from_games/code/read_mapping.zip) of [GTA5](https://download.visinf.tu-darmstadt.de/data/from_games/)，and `split.mat` in the `read_mapping` folder
