### ISSUE TITLE
The method does not have domain alignment that works so well.

### ISSUE THREAD

**Issue by jingzhengli** [microsoft/ProDA#15]
Hi, I am amazed that this algorithm does not have **domain alignment** that can work so well. Is domain alignment important? Thus what I want to know is: which category prototype of the source data or the category prototype of the target data is used in the experiment. Which of the two works better: the category prototype of the source data and the target data?

**Comment by panzhang0212** [comment]
In our experiment, category prototypes initialized by source data or target data give similar performance. And we update the prototype using target data and do not try source data. To my knowledge, aligning two domains does not always give better performance. You can refer to [this paper](https://openaccess.thecvf.com/content_cvpr_2018/papers/Saito_Maximum_Classifier_Discrepancy_CVPR_2018_paper.pdf) for more detail.
