### ISSUE TITLE
Results of SYNTHIA2Cityscapes in each stage

### ISSUE THREAD

**Issue by super233** [microsoft/ProDA#18]
Hi, have you recorded the results of SYNTHIA2Cityscapes in each stage? If yes, would you please report them here?

**Comment by panzhang0212** [comment]
Warm-up log:
[run_2020_09_14_08_02_46.log](https://github.com/microsoft/ProDA/files/6661751/run_2020_09_14_08_02_46.log)
Stage 1 log:
[run_2020_09_24_02_12_41.log](https://github.com/microsoft/ProDA/files/6661776/run_2020_09_24_02_12_41.log)
Stage 2 log:
[run_2020_11_12_08_23_40.log](https://github.com/microsoft/ProDA/files/6661763/run_2020_11_12_08_23_40.log)
Stage 3 log:
[run_2020_11_14_08_58_23.log](https://github.com/microsoft/ProDA/files/6661768/run_2020_11_14_08_58_23.log)

**Comment by super233** [comment]
Thanks a lot.
