### ISSUE TITLE
Amount of epochs for both source only and warm-up stage

### ISSUE THREAD

**Issue by fabriziojpiva** [microsoft/ProDA#21]
Hi, I am trying to reproduce the full pipeline from the very beginning, i.e. starting from training the model only with the source dataset, then doing the warm-up stage and so on.

Could you provide more information about the amount of epochs or iterations that you trained the model for the following stages:

1. Source only
2. Warm-up

Thanks for the help.

**Comment by panzhang0212** [comment]
Hi, the training iterations of the two stages are the same with the stage 1/2/3.
In my experience, you could directly train the warm-up stage (init from ImageNet), which is comparable with Source only + Warm-up.

**Comment by valencebond** [comment]
hi, @fabriziojpiva @panzhang0212 how can I train a model only with the source datasets?  Can you provide some scripts that I can refer to? thanks
