### ISSUE TITLE
the classifier is replaced with an enhanced version with SE module ?

### ISSUE THREAD

**Issue by DZhaoXd** [microsoft/ProDA#25]
The paper states: 'We use the DeepLabv2 [8] for segmentation with the backbone ResNet-101 [25]'.  However, in the code, the last classifier is replaced with an enhanced version with SE module.  The enhanced network structure may further improve the performance of UDA.  Will this lead to an unfair comparison with deeplabv2 in other works?

**Comment by panzhang0212** [comment]
just noticed another issue on the same topic [here,](https://github.com/microsoft/ProDA/issues/2#issue-856581132) so I am closing this one.
