### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by y72428026** [microsoft/ProDA#26]
hello~Thanks for your excellent work, but now I meet a problem when I try to follow the steps in "Inference Using Pretrained Model"-"2) GTA -> Cityscapes". It throws a error:
     RuntimeError: Error(s) in loading state_dict for ResNet101:
        Missing key(s) in state_dict: "bn_pretrain.weight", "bn_pretrain.bias", "bn_pretrain.running_mean", "bn_pretrain.running_var". 
![image](https://user-images.githubusercontent.com/33658126/123915365-015a4a80-d9b3-11eb-87af-0a3745ebc640.png)
if  anyone meet the same error?

**Comment by JiangXiaobai00** [comment]
I also encounter this problem !

**Comment by ljjcoder** [comment]
I also encounter this problem ! Anyone fixed it？

**Comment by michaelku1** [comment]
the downloaded pretrained weights have those keys where your initialised model is missing, so you need to go to the line where stage1 model is initialised and add the bn_clr=opt.bn_clr to it, and then you will have to specify --bn_clr in your command line to flag bn_clr to True (bn_clr is a batchnorm layer)
