### ISSUE TITLE
Have you been trained with source only? 

### ISSUE THREAD

**Issue by junha1125** [microsoft/ProDA#32]
Hi. 
Thank you to share your perfect code.

I am running your code. And I met one issue that can be relatived with 
the problem in your paper, that ProDA's "train class mIoU score" was Zero.

## 1. Adding this to your code
ProDA/models/adaptation_modelsv2.py
this is for **source only training**
```python
class CustomModel():
    def step_source(self, source_x, source_label, source_imageS=None, source_params=None):
        self.BaseOpti.zero_grad()
        
        if self.opt.S_pseudo_src > 0: # Always [opt.S_pseudo_src == 0]
            source_output = self.BaseNet_DP(source_imageS)
            source_label_d4 = F.interpolate(source_label.unsqueeze(1).float(), size=source_output['out'].size()[2:])
            source_labelS = self.label_strong_T(source_label_d4.clone().float(), source_params, padding=250, scale=4).to(torch.int64)
            loss_ = cross_entropy2d(input=source_output['out'], target=source_labelS.squeeze(1))
            loss_GTA = loss_ * self.opt.S_pseudo_src
            source_outputUp = F.interpolate(source_output['out'], size=source_x.size()[2:], mode='bilinear', align_corners=True)
        else: # Runing part
            source_output = self.BaseNet_DP(source_x, ssl=True)
            source_outputUp = F.interpolate(source_output['out'], size=source_x.size()[2:], mode='bilinear', align_corners=True)
            loss_GTA = cross_entropy2d(input=source_outputUp, target=source_label, size_average=True, reduction='mean')

        loss_GTA.backward()
        self.BaseOpti.step()

        return loss_GTA.item()
```

## 2. Result to train with source only
But I got this result.
![image](https://user-images.githubusercontent.com/46951365/126422315-cf570018-5737-4948-93d3-35eae394748b.png)

## 3. the main issue
I've never seen a few classes score 0.
But If we see the result above, we can see Zero score.
**How do you think about this??**

Thank you.

---
---
### PS: Runging config
```sh
init_parameter = 'imagenet'

# gta5 / synthia / cityscapes
src_dataset = 'gta5' 
tgt_dataset = 'gta5'
# GTA5 / Synthia / Cityscapes
src_rootpath = 'Dataset/GTA5'
tgt_rootpath = 'Dataset/GTA5'
n_class = 19
num_workers = 8
bs = 8

name = 'gta5_src'
seed = 1337

## model
model_name = 'deeplabv2'
lr = 0.0005
freeze_bn = False
epochs = 84
train_iters = 90000
bn = 'sync_bn'
no_resume = False
stage = 'src_only' # warm_up / stage1 / stage2 or stage3 / src_only 
finetune = False
bn_clr = False
train_thred = 0
used_save_pseudo = False
no_droplast = False

resize = 2200
rcrop = [896, 512]
hflip = 0.5

S_pseudo = 0.0

noshuffle = False
noaug = False

```

**Comment by yasserben** [comment]
Hi @junha1125 , I would like to know if you managed to solve this problem, because I am having the same issue.
The mIoU of three classes are equal to 0, and it's exactly the same classes you had too.
Thanks !!

**Comment by junha1125** [comment]
HI! @yasserben, unfortunately, I could not solve that problem so that I recommend referring [CRST](https://github.com/yzou2/CRST) or [IAST](https://github.com/Raykoooo/IAST) code, where they provide a pre-trained model on the source dataset. In ProDA code, It seems that an additional method to solve the class-inbalance issue needs to be applied. I am sorry that I can not give you an exact solution.
Best wishes,
