### ISSUE TITLE
deeplabv2.py code problem

### ISSUE THREAD

**Issue by engine210** [microsoft/ProDA#33]
Hi, I'm curious about a line of code in deeplabv2.py
https://github.com/microsoft/ProDA/blob/9ba80c7dbbd23ba1a126e3f4003a72f27d121a1f/models/deeplabv2.py#L123
It seems like `return out` has an extra indent which makes for loop useless. Or does it has some purpose?

```py
    def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list) - 1):
            out += self.conv2d_list[i + 1](x)
            return out
```

**Comment by luyvlei** [comment]
In fact, performance rely on this bug.

**Comment by panzhang0104** [comment]
The code of the model is borrowed from [seg-Uncertainty](https://github.com/layumi/Seg-Uncertainty). For the reason, please refer to https://github.com/microsoft/ProDA/issues/2#issuecomment-818481201
