### ISSUE TITLE
Training Stage Loss

### ISSUE THREAD

**Issue by JunkunPeng17** [microsoft/ProDA#37]
Dear author，
        Thanks for your great work. Recently I do the code reproduction and fine a small issue which I'm not sure. When I finish the stage1 training and start to train the stage2 I found that the loss will be negative in some cases. After checking the loss code part I thought it will not be negative theoretically. May you know what the problem is or it is not a problem due to my poor knowledge.
![loss](https://user-images.githubusercontent.com/56396894/140469840-4441b59c-e13e-4e95-8d4d-d126b6c88924.jpg)

**Comment by panzhang0104** [comment]
The loss includes KLDivLoss which may get a negative loss

**Comment by JunkunPeng17** [comment]
Okay, I got it. Thanks for your reply
