### ISSUE TITLE
About the flip Image

### ISSUE THREAD

**Issue by JunXieFront** [microsoft/ProDA#44]
```python      
if opt.flip:
    flip_out = model.BaseNet_DP(fliplr(images_val))
    flip_out['out'] = F.interpolate(sm(flip_out['out']), size=images_val.size()[2:], mode='bilinear', align_corners=True)
    out['out'] = F.interpolate(sm(out['out']), size=images_val.size()[2:], mode='bilinear', align_corners=True)
    out['out'] = (out['out'] + fliplr(flip_out['out'])) / 2
```
Dear author，thanks for sharing the code with us. I don't the reason why we should flip the image and compute **flip_out** here, If it can help increasing the performance, why not using it in generating soft label at first time?

**Comment by QChhh123** [comment]
Hi, can you tell me the reason? Thank you very much.
